### PR TITLE
Use config to gate mutating hooks

### PR DESCRIPTION
**Pull request by ptnapoleon**
## What does this PR do?

- [ ] Adds new functionality
- [ ] Alters existing functionality
- [ ] Fixes a bug
- [ ] Improves documentation or testing

Please briefly describe your changes as well as the motivation behind them:
- Dont initialize the handler webhook if the handler is disabled
- Require a config option to initialize the user info webhook

## Code Quality Checklist

- [ ] The documentation is up to date.
- [ ] My code is sufficiently commented and passes continuous integration checks.
- [ ] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md)).

## Testing

- [ ] I leveraged continuous integration testing
    - [ ] by depending on existing `unit` tests or `end-to-end` tests.
    - [ ] by adding new `unit` tests or `end-to-end` tests.
- [ ] I manually tested the following steps:
    - `x`
    - [ ] locally.
    - [ ] as a canary deployment to a cluster.

### CODE REVIEW

**Comment by nikos912000** [comment]
Thanks for that!

Two comments:
- Can we also update the [Slack notifier](https://github.com/DataDog/chaos-controller/blob/349e69d37ae7c809a93f355b9b2b7eea5e823a4d/eventnotifier/slack/slack.go#L112) which expects the UserInfo to be there?
- The scope of this PR includes the user info and pod init mutating webhooks. There is one more for the [duration](https://github.com/DataDog/chaos-controller/blob/349e69d37ae7c809a93f355b9b2b7eea5e823a4d/api/v1beta1/disruption_webhook.go#L48). It'd be great to have that behind a flag as well.

PS: I like the idea of having separate flags; the one for the Duration is more critical, regardless of the fact that we may need to disable that internally.

**Review by Devatoria — APPROVED** [review]

**Comment by ptnapoleon** [comment]
> Can we also update the [Slack notifier](https://github.com/DataDog/chaos-controller/blob/349e69d37ae7c809a93f355b9b2b7eea5e823a4d/eventnotifier/slack/slack.go#L112) which expects the UserInfo to be there?

Seems that the slack notifier just needs disabled if it always requires the UserInfo to be present?

**Comment by nikos912000** [comment]
> Seems that the slack notifier just needs disabled if it always requires the UserInfo to be present?

I'd say the user info is complementary there? It would still be useful without that info.

**Comment by nikos912000** [comment]
> Seems that the slack notifier just needs disabled if it always requires the UserInfo to be present?

I'd say the user info is complementary there? It would still be useful without that info.

**Comment by ptnapoleon** [comment]
@nikos912000 Without setting a default duration (because we've disabled the mutating webhook), it seems that nothing errors, but any disruption without a duration set will immediately be considered expired. Are you planning on always having `spec.duration` set? Is there a way we can fix the webhook such that it doesnt cause problems for you?

**Comment by ptnapoleon** [comment]
> I'd say the user info is complementary there? It would still be useful without that info.

Right now it only knows who to send the slack message to based on the UserInfo. We could add a config value for a slack channel to send all these updates to?

**Comment by nikos912000** [comment]
> @nikos912000 Without setting a default duration (because we've disabled the mutating webhook), it seems that nothing errors, but any disruption without a duration set will immediately be considered expired. Are you planning on always having `spec.duration` set? Is there a way we can fix the webhook such that it doesnt cause problems for you?

Our intention is to always set the duration on the Spinnaker side.
Happy to keep the duration mutating webhook for now and until we have a clear ask for that :)

**Comment by nikos912000** [comment]
> > I'd say the user info is complementary there? It would still be useful without that info.
> 
> Right now it only knows who to send the slack message to based on the UserInfo. We could add a config value for a slack channel to send all these updates to?

Oh ok. To be fair we haven't enabled the Slack integration (yet).
Whatever is easier for you. We can always update that later.

**Comment by ptnapoleon** [comment]
In that case, I'm going to merge the current PR as-is. I'll open a ticket internally for "Let slack notifier be useful even w/o user info".

**Pull request merged**
