### PR TITLE
Fix link to metrics documentation in README

### PR DESCRIPTION
**Pull request by youvegotmoxie**
Signed-off-by: Michael Beasley <michael.beasley@alvaria.com>

## What does this PR do?

- [ ] Adds new functionality
- [ ] Alters existing functionality
- [ ] Fixes a bug
- [x] Improves documentation or testing

Please briefly describe your changes as well as the motivation behind them:
- This PR fixes the link to the metrics documentation in the repo's README

## Code Quality Checklist

- [N/A] The documentation is up to date.
- [N/A] My code is sufficiently commented and passes continuous integration checks.
- [x] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md)).

## Testing

- [N/A] I leveraged continuous integration testing
    - [N/A] by depending on existing `unit` tests or `end-to-end` tests.
    - [N/A] by adding new `unit` tests or `end-to-end` tests.
- [N/A] I manually tested the following steps:
    - `x`
    - [N/A] locally.
    - [N/A] as a canary deployment to a cluster.

### CODE REVIEW

**Review by taihuynh167 — APPROVED** [review]
thanks 🙇

**Review by aymericDD — APPROVED** [review]
Thanks :+1:

**Comment by aymericDD** [comment]
Can you sign your commit @youvegotmoxie. Otherwise the PR could not be merged.

**Comment by youvegotmoxie** [comment]
I resigned the commit with my SSH key and used the email associated with GitHub account but I can't seem to make the PR bot happy. I'm going to redo this with another PR.

**Pull request closed without merging**
