### PR TITLE
CHAOSPLT-201: Send disruption completion events by default

### PR DESCRIPTION
**Pull request by ptnapoleon**
## What does this PR do?

- [ ] Adds new functionality
- [ ] Alters existing functionality
- [ ] Fixes a bug
- [ ] Improves documentation or testing

Please briefly describe your changes as well as the motivation behind them:
- The default reporting type is Success, let's consider completing a disruption as a Success

## Code Quality Checklist

- [ ] The documentation is up to date.
- [ ] My code is sufficiently commented and passes continuous integration checks.
- [ ] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md)).

## Testing

- [ ] I leveraged continuous integration testing
    - [ ] by depending on existing `unit` tests or `end-to-end` tests.
    - [ ] by adding new `unit` tests or `end-to-end` tests.
- [ ] I manually tested the following steps:
    - `x`
    - [ ] locally.
    - [ ] as a canary deployment to a cluster.

### CODE REVIEW

**Comment by ptnapoleon** [comment]
Turns out calling these successes isn't a good idea, they show up as "recoveries"

**Comment by ptnapoleon** [comment]
I think I want to split the message for recoveries and completions, one more commit...

**Review by Devatoria — APPROVED** [review]
Nice, LGTM

**Review by aymericDD — APPROVED** [review]
💯

**Pull request merged**
