### PR TITLE
Makes the status a subresource in the CRD.

### PR DESCRIPTION
**Pull request by expFlower**
Signed-off-by: David Fowler <dafowler@expediagroup.com>

## What does this PR do?

- [ ] Adds new functionality
- [x] Alters existing functionality
- [ ] Fixes a bug
- [ ] Improves documentation or testing

Please briefly describe your changes as well as the motivation behind them:
- Makes the status a subresource in the CRD. See https://github.com/DataDog/chaos-controller/issues/511.
- Store UserInfo in annotations

## Code Quality Checklist

- [ ] The documentation is up to date.
- [ ] My code is sufficiently commented and passes continuous integration checks.
- [ ] I have signed my commit (see [Contributing Docs](../CONTRIBUTING.md)).

## Testing

- [ ] I leveraged continuous integration testing
    - [ ] by depending on existing `unit` tests or `end-to-end` tests.
    - [ ] by adding new `unit` tests or `end-to-end` tests.
- [ ] I manually tested the following steps:
    - [x] locally.
    - [ ] as a canary deployment to a cluster.

### CODE REVIEW

**Comment by expFlower** [comment]
@ptnapoleon @Devatoria , working with @nikos912000 on the implementing status as a subresource while preserving the UserInfo and it would be good to get some feedback:

The UserInfo is stored as an annotation, which poses a couple of questions:
-  it's unmarshalled upon each getmetricsTags call (validateCreate, validateUpdate, validateDelete) which could potentially be an expensive operation.  Would you see this as an issue? 

- UserInfo is used in slack integration which would again require an unmarshal operation to extract the UserInfo again.  We could unmarshal the UserInfo back into the DisruptionStatus to make it easily available again?

**Comment by ptnapoleon** [comment]
@expFlower This certainly looks great to me, and it seems to be working when I test it locally. Would you be alright if I pushed a copy to my own branch, so that I can test it internally? Thanks!

**Comment by ptnapoleon** [comment]
> it's unmarshalled upon each getmetricsTags call (validateCreate, validateUpdate, validateDelete) which could potentially be an expensive operation. Would you see this as an issue?

> UserInfo is used in slack integration which would again require an unmarshal operation to extract the UserInfo again. We could unmarshal the UserInfo back into the DisruptionStatus to make it easily available again?

Personally, I am not concerned about the cost of those operations

**Comment by expFlower** [comment]
> @expFlower This certainly looks great to me, and it seems to be working when I test it locally. Would you be alright if I pushed a copy to my own branch, so that I can test it internally? Thanks!

Absolutely, please do. 

There's the slack.go implementation to work out and depending how that's done the DisruptionStatus / CRD would need to be cleaned up / updated.

**Comment by expFlower** [comment]
Closing this PR, implementation completed through #520

**Pull request closed without merging**
